version: '3'
services:
  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    depends_on:
      - db-mongo
    ports: 
      - "2000:2000"
    volumes:
      - ./output:/output
    networks:
      - mock-network
  
  db-mongo:
    image: 'mongo'
    container_name: 'db-mongo'
    environment:
      - MONGO_INITDB_DATABASE=pikmin-database
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./go/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-volume-container:/data/db
    ports:
      - '27017:27017'
    networks:
      - mock-network

networks:
  mock-network:
volumes:
  mongo-volume-container: